"""
Data Analyst Agent — Handles all structured database queries.
Uses create_react_agent for multi-step tool reasoning with automatic
tool calling loops. Generates its own subgraph diagram.
"""
import pathlib
from langgraph.prebuilt import create_react_agent
from core.factory import get_llm
from core.state import GraphState
from core.logger import logger
from db.schema import get_bcnf_schema, get_table_names
from tools.sql import (
    execute_read_query,
    list_database_tables,
    describe_table_schema,
    cache_dashboard_metric,
)


def sql_node(state: GraphState) -> dict:
    """
    Data Analyst sub-agent node. Builds a ReAct agent with SQL tools
    and invokes it on the current conversation state.

    Steps:
    1. Dynamically fetches current database schema.
    2. Creates a ReAct agent with all SQL tools.
    3. Executes the agent and returns only new messages.
    """
    llm = get_llm(temperature=0)
    tools = [
        execute_read_query,
        list_database_tables,
        describe_table_schema,
        cache_dashboard_metric,
    ]

    # Retrieve dynamic schema context
    table_names = get_table_names()
    schema_context = get_bcnf_schema(table_names)

    sys_msg = f"""You are the Data Analyst Agent for an executive project dashboard.
Your job is to answer questions by querying the project database accurately.

DATABASE SCHEMA:
{schema_context}

AVAILABLE TOOLS:
1. list_database_tables — Discover all available tables.
2. describe_table_schema — Get DDL and column names for a specific table.
3. execute_read_query — Execute a SELECT query.
4. cache_dashboard_metric — Save an important finding for the dashboard.

WORKFLOW:
1. If unsure about table structure, use describe_table_schema first.
2. Write your SELECT query with EXPLICIT column names. Never use SELECT *.
3. Use proper JOINs when data spans multiple tables.
4. Interpret the results and provide a clear, concise executive summary.
5. If you find critical/at-risk items, use cache_dashboard_metric to flag them.
6. Once you have the answer, state it clearly. DO NOT ask the user for more info if the data is already there.

SQL RULES (STRICT):
- FORBIDDEN: SELECT * — always name columns explicitly.
- FORBIDDEN: Any DML (INSERT/UPDATE/DELETE/DROP).
- REQUIRED: Use table_name.column_name when joining.
- RECOMMENDED: Use LIMIT for large tables.
- FINAL ACTION: Your last message MUST be a clear answer to the user's question based on the data found.
"""

    try:
        agent_executor = create_react_agent(llm, tools, state_modifier=sys_msg)

        # Save subgraph diagram
        try:
            out_dir = pathlib.Path("graph_img")
            out_dir.mkdir(exist_ok=True)
            with open(out_dir / "sql_agent_latest.png", "wb") as f:
                f.write(agent_executor.get_graph().draw_mermaid_png())
        except Exception:
            pass

        # ROOT FIX: Prune messages to stay within Groq TPM limits
        all_messages = state["messages"]
        if len(all_messages) > 12:
            pruned_messages = [all_messages[0]] + list(all_messages[-10:])
        else:
            pruned_messages = list(all_messages)

        # Capture original length BEFORE invocation to avoid mutation bugs
        # We use the length of pruned_messages because that's what the agent executor starts with
        pruned_len = len(pruned_messages)
        result = agent_executor.invoke({"messages": pruned_messages})

        # Return only new messages generated by this agent
        all_messages_after = result["messages"]
        if len(all_messages_after) > pruned_len:
            new_messages = all_messages_after[pruned_len:]
        else:
            # If for some reason it's shorter or same length, assume no new messages
            new_messages = []
        
        logger.info(
            "SQL Agent finished",
            in_count=len(state["messages"]),
            out_count=len(all_messages_after),
            new_count=len(new_messages)
        )
        
        # If the agent produced no new messages, it might be stuck or 
        # think it already answered. Add a fallback message to break loops.
        if not new_messages:
            from langchain_core.messages import SystemMessage
            new_messages = [SystemMessage(content="[SYSTEM] SQL Agent reviewed the history and found no new actions needed.")]

        return {"messages": new_messages}

    except Exception as e:
        logger.exception("SQL Agent execution failed")
        from langchain_core.messages import AIMessage
        return {
            "messages": [AIMessage(content=f"Data Analyst Error: {str(e)}. Please try rephrasing your question.")]
        }