"""
Executive Document Generation Tool.
Creates premium, well-formatted PDFs for Meeting Summaries, RFPs, and SOWs.
Uses fpdf2 for high-quality executive layouts.
"""
import os
import uuid
import datetime
from fpdf import FPDF
from langchain_core.tools import tool
from langchain_core.runnables import RunnableConfig
from core.schemas import GenerateReportSchema
from core.logger import logger
from core.config import settings
from core.session import REPORTS_TEMP_DIR








TEMPLATES = {
    "Executive Gold": {
        "primary": (15, 23, 42), # Slate 900
        "accent": (197, 165, 114), # Gold
        "bg": (252, 252, 253), # Off-white
        "text": (51, 65, 85), # Slate 700
        "highlight": (248, 250, 252) # Slate 50
    },
    "Modern Blue": {
        "primary": (30, 58, 138), # Blue 900
        "accent": (59, 130, 246), # Blue 500
        "bg": (240, 249, 255), # Blue 50
        "text": (30, 41, 59), # Slate 800
        "highlight": (219, 234, 254) # Blue 100
    },
    "Classic Slate": {
        "primary": (2, 6, 23), # Slate 950
        "accent": (71, 85, 105), # Slate 600
        "bg": (255, 255, 255), # White
        "text": (15, 23, 42), # Slate 900
        "highlight": (241, 245, 249) # Slate 100
    },
    "Urgent Red": {
        "primary": (127, 29, 29), # Red 900
        "accent": (220, 38, 38), # Red 600
        "bg": (254, 242, 242), # Red 50
        "text": (69, 10, 10), # Red 950
        "highlight": (254, 226, 226) # Red 100
    }
}

class ExecutivePDF(FPDF):
    def __init__(self, template="Executive Gold"):
        super().__init__()
        self.template_name = template
        self.colors = TEMPLATES.get(template, TEMPLATES["Executive Gold"])
        self.set_margins(20, 25, 20)
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        # Premium thin bar at the top
        self.set_fill_color(*self.colors["primary"])
        self.rect(0, 0, 210, 3, "F")
        
        if self.page_no() == 1:
            self.set_font("helvetica", "B", 8)
            self.set_text_color(148, 163, 184)
            self.set_y(12)
            self.cell(0, 10, "ORBIT INTELLIGENCE ENGINE  |  CONFIDENTIAL EXECUTIVE AUDIT", align="R")
            self.ln(20)

    def footer(self):
        self.set_y(-20)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        date_str = datetime.datetime.now().strftime("%B %d, %Y")
        self.cell(0, 10, f"Page {self.page_no()} of {{nb}}  |  {date_str}  |  Generated by Orbit AI", align="C")

def parse_markdown_table(block: str) -> list[list[str]]:
    """Parses a markdown table into a list of rows."""
    lines = block.strip().split('\n')
    table_data = []
    for line in lines:
        line = line.strip()
        if not line or set(line.replace('|', '').replace('-', '').replace(' ', '')) == set():
            continue
        if line.startswith('|'):
            line = line[1:]
        if line.endswith('|'):
            line = line[:-1]
        row = [cell.strip() for cell in line.split('|')]
        table_data.append(row)
    return table_data

def generate_pdf(doc_type, title, subtitle, content_markdown, filepath, template_name="Executive Gold"):
    """
    Advanced Executive PDF Engine.
    Handles 'Responsive' Tables: 
    - Horizontal for <= 5 columns.
    - Vertical Key-Value pairs for > 5 columns (prevents overflow).
    """
    pdf = ExecutivePDF(template=template_name)
    colors = pdf.colors
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # 1. Premium Cover Header
    pdf.set_font("helvetica", "B", 26)
    pdf.set_text_color(*colors["primary"])
    pdf.multi_cell(0, 14, title.upper(), align="L")
    
    if subtitle:
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(*colors["accent"])
        pdf.cell(0, 10, subtitle, ln=1, align="L")
        
    pdf.ln(5)
    pdf.set_draw_color(*colors["accent"])
    pdf.set_line_width(1)
    pdf.line(20, pdf.get_y(), 80, pdf.get_y())
    pdf.ln(15)
    
    # 2. Content Engine
    import re
    # Convert markdown bold to PDF compatible (subtle)
    content_markdown = re.sub(r'\*\*(.*?)\*\*', r'__BOLD__\1__BOLD__', content_markdown)
    blocks = content_markdown.split("\n\n")
    
    for block in blocks:
        block = block.strip()
        if not block: continue
        
        # --- Advanced Table Logic ---
        if "|" in block and "---" in block:
            table_data = parse_markdown_table(block)
            if not table_data: continue
            
            headers = table_data[0]
            rows = table_data[1:]
            col_count = len(headers)
            
            # DECISION: Horizontal or Vertical?
            if col_count <= 5:
                # HORIZONTAL RENDER
                pdf.set_font("helvetica", "B", 9)
                pdf.set_fill_color(*colors["highlight"])
                pdf.set_text_color(*colors["primary"])
                
                col_width = pdf.epw / col_count
                for h in headers:
                    pdf.cell(col_width, 10, str(h).upper(), border=1, fill=True, align="C")
                pdf.ln()
                
                pdf.set_font("helvetica", "", 8)
                pdf.set_text_color(*colors["text"])
                for row in rows:
                    # Calculate max height needed for this row
                    max_h = 8
                    for cell in row:
                        # Estimate lines
                        lines = pdf.get_string_width(str(cell)) / col_width
                        max_h = max(max_h, (int(lines) + 1) * 5)
                    
                    if pdf.get_y() + max_h > 270: pdf.add_page()
                    
                    for cell in row:
                        x, y = pdf.get_x(), pdf.get_y()
                        pdf.multi_cell(col_width, 5, str(cell).strip(), border=1, align="L")
                        pdf.set_xy(x + col_width, y)
                    pdf.ln(max_h)
            else:
                # VERTICAL RENDER (The "No Space" Fix)
                pdf.set_font("helvetica", "B", 10)
                pdf.set_text_color(*colors["accent"])
                pdf.cell(0, 10, "DATA SUMMARY (Vertical Layout)", ln=1)
                
                for i, row in enumerate(rows):
                    pdf.set_fill_color(*colors["highlight"])
                    pdf.set_font("helvetica", "B", 8)
                    pdf.set_text_color(*colors["primary"])
                    pdf.cell(0, 7, f"ENTRY #{i+1}", ln=1, fill=True)
                    
                    pdf.set_font("helvetica", "", 8)
                    for h, val in zip(headers, row):
                        pdf.set_font("helvetica", "B", 8)
                        pdf.set_text_color(*colors["primary"])
                        pdf.cell(40, 6, f"{h}:", ln=0)
                        pdf.set_font("helvetica", "", 8)
                        pdf.set_text_color(*colors["text"])
                        pdf.multi_cell(0, 6, str(val).strip())
                    pdf.ln(3)
            pdf.ln(5)
            continue

        # --- Headers ---
        if block.startswith("#"):
            level = len(re.match(r'^#+', block).group())
            text = block.replace("#", "").strip()
            
            if level == 1:
                pdf.set_font("helvetica", "B", 18)
                pdf.set_text_color(*colors["primary"])
                pdf.ln(8)
                pdf.cell(0, 12, text, ln=1)
            elif level == 2:
                pdf.set_font("helvetica", "B", 14)
                pdf.set_text_color(*colors["primary"])
                pdf.ln(5)
                pdf.cell(0, 10, text, ln=1)
            else:
                pdf.set_font("helvetica", "B", 11)
                pdf.set_text_color(*colors["accent"])
                pdf.ln(3)
                pdf.cell(0, 8, text, ln=1)
            continue

        # --- Standard Paragraph ---
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(*colors["text"])
        # Simple Bold Replacement
        clean_block = block.replace("__BOLD__", "")
        pdf.multi_cell(0, 6, clean_block)
        pdf.ln(3)
            
    pdf.output(filepath)

def generate_docx(doc_type, title, subtitle, content_markdown, filepath):
    """Professional DOCX Export."""
    from docx import Document
    from docx.shared import Pt, RGBColor
    
    document = Document()
    
    title_pg = document.add_heading(title.upper(), 0)
    title_pg.style.font.color.rgb = RGBColor(15, 23, 42)
    
    if subtitle:
        p = document.add_paragraph()
        runner = p.add_run(subtitle)
        runner.font.size = Pt(14)
        runner.font.color.rgb = RGBColor(197, 165, 114)
        
    document.add_paragraph()
    
    blocks = content_markdown.split("\n\n")
    for block in blocks:
        block = block.strip()
        if not block: continue
        
        if "|" in block and "---" in block:
            table_data = parse_markdown_table(block)
            if table_data and len(table_data) > 0:
                table = document.add_table(rows=1, cols=len(table_data[0]))
                table.style = 'Table Grid'
                hdr_cells = table.rows[0].cells
                for i, header in enumerate(table_data[0]):
                    if i < len(hdr_cells):
                        hdr_cells[i].text = header
                for row in table_data[1:]:
                    row_cells = table.add_row().cells
                    for i, cell in enumerate(row):
                        if i < len(row_cells):
                            row_cells[i].text = cell
            continue
            
        if block.startswith("#"):
            level = len(block) - len(block.lstrip('#'))
            text = block.replace("#", "").strip()
            document.add_heading(text, level=min(level, 9))
            continue
            
        document.add_paragraph(block.replace('__BOLD__', ''))
        
    document.save(filepath)

def generate_image(title, subtitle, content_markdown, filepath, template_name="Executive Gold"):
    """Premium Glassmorphism Image Generator."""
    from html2image import Html2Image
    hti = Html2Image(output_path=os.path.dirname(filepath))
    
    colors = TEMPLATES.get(template_name, TEMPLATES["Executive Gold"])
    c_primary = f"rgb{colors['primary']}"
    c_accent = f"rgb{colors['accent']}"
    c_bg = f"rgb{colors['bg']}"
    
    import markdown
    html_content = markdown.markdown(content_markdown, extensions=['tables'])
    
    html = f"""
    <html>
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap" rel="stylesheet">
        <style>
            body {{ font-family: 'Outfit', sans-serif; background: {c_bg}; color: #0f172a; padding: 50px; margin: 0; width: 850px; }}
            .container {{ position: relative; background: rgba(255, 255, 255, 0.8); backdrop-filter: blur(10px); border-radius: 24px; padding: 50px; border: 1px solid rgba(255,255,255,0.4); box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.1); }}
            .accent-bar {{ position: absolute; top: 0; left: 50px; right: 50px; height: 6px; background: {c_accent}; border-radius: 0 0 10px 10px; }}
            h1 {{ font-size: 42px; font-weight: 700; color: {c_primary}; margin: 0; line-height: 1.1; letter-spacing: -0.02em; }}
            .subtitle {{ font-size: 18px; color: {c_accent}; font-weight: 600; margin-top: 10px; text-transform: uppercase; letter-spacing: 0.1em; }}
            .content {{ margin-top: 40px; font-size: 16px; color: #334155; line-height: 1.6; }}
            table {{ width: 100%; border-collapse: separate; border-spacing: 0; margin: 25px 0; border-radius: 12px; overflow: hidden; border: 1px solid #e2e8f0; }}
            th {{ background: #f8fafc; color: {c_primary}; padding: 15px; text-align: left; font-size: 12px; text-transform: uppercase; border-bottom: 2px solid {c_accent}; }}
            td {{ background: white; padding: 15px; border-bottom: 1px solid #f1f5f9; font-size: 14px; }}
            tr:last-child td {{ border-bottom: none; }}
            .footer {{ margin-top: 50px; font-size: 11px; color: #94a3b8; font-weight: 600; display: flex; justify-content: space-between; border-top: 1px solid #e2e8f0; padding-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="accent-bar"></div>
            <h1>{title}</h1>
            <div class="subtitle">{subtitle or 'Confidential Intelligence Report'}</div>
            <div class="content">{html_content}</div>
            <div class="footer">
                <span>ORBIT AI INTELLIGENCE</span>
                <span>{datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}</span>
            </div>
        </div>
    </body>
    </html>
    """
    hti.screenshot(html_str=html, save_as=os.path.basename(filepath), size=(950, 1200))

def generate_excel(content_markdown, filepath):
    """Professional Excel Export with OpenPyXL Styling."""
    import pandas as pd
    from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
    
    blocks = content_markdown.split("\n\n")
    with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
        sheet_count = 0
        for block in blocks:
            if "|" in block and "---" in block:
                table_data = parse_markdown_table(block)
                if len(table_data) > 1:
                    df = pd.DataFrame(table_data[1:], columns=table_data[0])
                    sheet_name = f"Data_{sheet_count + 1}"
                    df.to_excel(writer, sheet_name=sheet_name, index=False)
                    
                    # Apply Styling
                    ws = writer.sheets[sheet_name]
                    header_fill = PatternFill(start_color="0F172A", end_color="0F172A", fill_type="solid")
                    header_font = Font(color="FFFFFF", bold=True)
                    
                    for cell in ws[1]:
                        cell.fill = header_fill
                        cell.font = header_font
                        cell.alignment = Alignment(horizontal="center")
                    
                    # Auto-adjust column widths
                    for col in ws.columns:
                        max_length = 0
                        column = col[0].column_letter
                        for cell in col:
                            try:
                                if len(str(cell.value)) > max_length:
                                    max_length = len(str(cell.value))
                            except: pass
                        adjusted_width = (max_length + 2)
                        ws.column_dimensions[column].width = min(adjusted_width, 50)
                    
                    sheet_count += 1
        
        if sheet_count == 0:
            pd.DataFrame({"Report Summary": [content_markdown]}).to_excel(writer, sheet_name="Report", index=False)

@tool(args_schema=GenerateReportSchema)
def generate_executive_report(doc_type: str, title: str, content_markdown: str, subtitle: str = None, format: str = "PDF", template_name: str = "Executive Gold", config: RunnableConfig = None) -> str:
    """
    Generates high-end executive reports in PDF, IMAGE, DOCX, or EXCEL format.
    The system uses responsive layout engines to handle large datasets without failing.
    """
    try:
        # Extract user context from config if available
        user_id = "unknown"
        if config:
            # If config is RunnableConfig or dict
            if hasattr(config, "get"):
                user_id = str(config.get("configurable", {}).get("user_id", "unknown"))
            elif isinstance(config, dict):
                user_id = str(config.get("configurable", {}).get("user_id", "unknown"))

        output_dir = REPORTS_TEMP_DIR
        os.makedirs(output_dir, exist_ok=True)
        
        safe_title = "".join(x for x in title if x.isalnum() or x in " -_").strip().replace(" ", "_")
        ext = format.lower()
        if ext == "excel": ext = "xlsx"
        if ext == "image": ext = "png"
        
        # Prefix filename with user_id for isolation
        filename = f"{user_id}_{safe_title}_{uuid.uuid4().hex[:6]}.{ext}"
        filepath = os.path.join(output_dir, filename)
        
        if format.upper() == "PDF":
            generate_pdf(doc_type, title, subtitle, content_markdown, filepath, template_name)
        elif format.upper() == "IMAGE":
            generate_image(title, subtitle, content_markdown, filepath, template_name)
        elif format.upper() == "EXCEL":
            generate_excel(content_markdown, filepath)
        elif format.upper() == "DOCX":
            generate_docx(doc_type, title, subtitle, content_markdown, filepath)
        else:
            return f"Error: Unsupported format '{format}'"
            
        download_url = f"http://localhost:8000/reports/download/{filename}"
        display_title = title if title and title.strip() else "Orbit Executive Report"
        return f"A premium **{template_name}** {format} has been generated: **[{display_title}]({download_url})**. Access it via the Executive Artifacts panel."

    except Exception as e:
        logger.error("Advanced Document Generation Failed", error=str(e))
        return f"Error: System failed to render the report. Reason: {str(e)}"


